### PR TITLE
Fix tmp .juvix-build creation in run command

### LINKED ISSUE #54: Clicking `run` doesn't work when `.juvix-build` doesn't exist
After clicking `run` in a Juvix file I get:
```
The terminal process failed to launch: Starting directory (cwd) "/Users/heliax/Documents/juvix-2/.juvix-build" does not exist.
```

### PR DESCRIPTION
**Pull request by vrom911**
After debugging, I found out that the problem was in the lack of permissions in a way we were creating tmp `.juvix-build` folder. 

With this change, it is fixed and currently it is working for me even when the `.juvix-build` folder doesn't exist.

* Resolves #54

### CODE REVIEW

File: src/config.ts [hunk 1]
```diff
@@ -66,21 +64,41 @@ export class JuvixConfig {
...
 
   public getInternalBuildDir(): string | undefined {
-    if (juvixBuildDir) return juvixBuildDir;
+
+    const useTmpDir = () => {
+      const tmpPath = path.join(tmpdir(), '.juvix-build');
+      try {
+        const tmp = fs.mkdtempSync(tmpPath);
+        const juvixBuildDir = tmp.toString();
+        console.log("TMP dir", juvixBuildDir);
```
Comment (jonaprieto) [inline src/config.ts:73]: You can use debugChannel.info here, so we can get all the logging info in the "output" panel.

File: src/config.ts [hunk 2]
```diff
@@ -66,21 +64,41 @@ export class JuvixConfig {
...
+        if (fs.existsSync(juvixBuildDir)) {
+          console.log("Directory exists.", juvixBuildDir)
+          return juvixBuildDir;
+        } else {
+          console.log("Directory does not exist.", juvixBuildDir)
+          const tmpJuvixDir = useTmpDir();
+          return tmpJuvixDir
+        }
+      } catch (e) {
+        console.log("An error occurred.", e)
```
Comment (jonaprieto) [inline src/config.ts:94]: debugChannel.error(..)

**Review by jonaprieto — APPROVED** [review]
